DROP TABLE IF EXISTS machines;
CREATE TABLE machines (
   id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
   os_id INT UNSIGNED NOT NULL,
   is_throttling TINYINT UNSIGNED NOT NULL DEFAULT '0',
   cpu_speed VARCHAR(255),
   name VARCHAR(255) NOT NULL,
   is_active TINYINT UNSIGNED NOT NULL DEFAULT '0',
   date_added INT UNSIGNED NOT NULL,

   PRIMARY KEY (id),
   UNIQUE KEY (name)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS branches;
CREATE TABLE branches (
   id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
   name VARCHAR(255) NOT NULL,

   PRIMARY KEY (id),
   UNIQUE KEY (name)
) ENGINE=InnoDB;
