#!/bin/sh
. /etc/mozconf
exec >> /var/log/mozilla-startup.log 2>&1
echo `date` - STARTING UP
echo ==================================================
#Try to get this device to always come back
rm /tmp/shutdown
touch /tmp/reboot

echo $CPUFREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo $CPUFREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
gconftool-2 --set /system/osso/dsm/display/enable_power_saving \
    --type bool false || booterror "gconftool-2"
gconftool-2 --set /system/osso/dsm/display/display_dim_timeout \
    --type int 99999999 || booterror "gconftool-2"
gconftool-2 --set /system/osso/dsm/display/display_blank_timeout \
    --type int 99999999 || booterror "gconftool-2"
gconftool-2 --set /system/osso/dsm/display/display_brightness \
    --type int 1 || booterror "gconftool-2"

dbus-uuidgen > /var/lib/dbus/machine-id

swapoff /swapfile || true
echo making swap file
dd if=/dev/zero of=/swapfile bs=1024 count=$(($SWAPSIZE * 1024)) || fatal 'dd swapfile'
echo formatting swap file
mkswap /swapfile || fatal 'mkswap'
echo activating swap
swapon /swapfile || fatal 'activating swap'

su - -c "/bin/uptime-check.py"
su - -c "/bin/run-ntp.py"
umount $BUILDDEV 2>/dev/null || true
mkdir -p $BUILDDIR
umount $BUILDDIR 2> /dev/null|| true
sync
sleep 2
mkfs.ext2 -L scratch $BUILDDEV -q || fatal 'formatting builds fs'
sync
sleep 2
mount -t ext2 $BUILDDEV $BUILDDIR

mkdir ${BUILDDIR}/profile

rm -rf /home/user/.mozilla
rm -rf /root/.mozilla
ln -s ${BUILDDIR}/profile /home/user/.mozilla
ln -s ${BUILDDIR}/profile /root/.mozilla

chown user:users -R /builds
su - user -c "buildbot create-slave --maxdelay=20 $BBDIR ${BBHOST}:${BBPORT} \
    $BBUSER $BBPASS"
cp $HWLOG $BBDIR/info/admin
killall nginx
/usr/nginx/sbin/nginx -c /usr/nginx/conf/nginx.conf || fatal "starting nginx"
if [[ -f $SENTINEL ]] ; then
    echo 'NOT STARTING BUILDBOT BECAUSE OF SENTINEL'
else
    su - user -c "buildbot start $BBDIR"
fi 
