#! /bin/sh
#
# skeleton	example file to build /etc/init.d/ scripts.
#		This file should be used to construct scripts for /etc/init.d.
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian 
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
# Version:	@(#)skeleton  1.9  26-Feb-2001  miquels@cistron.nl
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/ntpd
NAME=ntpd
DESC=openntpd

TMPFILE=/tmp/ntpd.$$
TIMEOUT=10
SUCCESS_STR='set local clock to'

test -x $DAEMON || exit 0

# Include openntpd defaults if available
if [ -f /etc/default/openntpd ] ; then
	. /etc/default/openntpd
fi

set -e

check_privsep_dir() {
    # check that the privsep dir exists
    if [ ! -d /var/run/openntpd ]; then
        mkdir /var/run/openntpd
        chmod 0755 /var/run/openntpd
    fi
}


case "$1" in
  start)
	check_privsep_dir
	echo -n "Running $DESC once: "
	start-stop-daemon --start --exec $DAEMON -- -sd > $TMPFILE 2>&1 &
	sleep $TIMEOUT
	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON
	grep -q "$SUCCESS_STR" $TMPFILE
	STATUS=$?
	rm $TMPFILE
	if [ $STATUS -eq 0 ] ; then
		/mnt/initfs/usr/bin/retutime --rtc-from-system 
		echo "$NAME."
	else
		echo "failed!"
		exit -1
	fi
	;;
  daemon-start)
	check_privsep_dir
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON
	echo "$NAME."
	;;
#  reload|force-reload)
	#
	#	If the daemon can reload its config files on the fly
	#	for example by sending it SIGHUP, do it here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this a do-nothing entry.
	#
#	echo "Reloading $DESC configuration files."
#	start-stop-daemon --stop --signal 1 --quiet --exec $DAEMON
#  	;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON
	sleep 1
	check_privsep_dir
	start-stop-daemon --start --quiet --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
