import cPickle
from slavealloc.data import model

def setup_argparse(subparsers):
    subparser = subparsers.add_parser('dbinit', help='initialize a fresh database')

    subparser.add_argument('dumpfile', nargs='?',
            help="""dump file as generated by 'slavealloc dbdump'; if not
            specified, then an empty database will be initialized.""")

    return subparser

def process_args(subparser, args):
    pass

def main(args):
    model.metadata.drop_all()
    model.metadata.create_all()

    if args.dumpfile:
        load_data(args)

def load_data(args):
    # see dbdump.py for the data format here
    dumpdict = cPickle.load(open(args.dumpfile))
    for tbl in model.metadata.sorted_tables:
        tname = tbl.name
        tbl = model.metadata.tables[tname]
        tbl.insert().execute(dumpdict[tname])
