#!/bin/sh

SENTINEL=/sentinel
HWLOG=/hwlog
CONFIGED=/config
HOST=`sed s/[.].*// < /etc/hostname`
BBHOST="production-mobile-master.build.mozilla.org"
BBPORT="9010"
BBUSER=$HOST
BBPASS='m0b1l3'
BUILDDIR=/builds
BUILDDEV=/home/builds-fs.ext2
SWAPDEV=/dev/mmcblk0p3

#Block buildbot, log failure and stop process
fatal () {
    echo "`date` FATAL: $@" | tee -a $SENTINEL $HWLOG > /dev/null
    echo "FATAL: $@"
    exit 1
}

#Block buildbot and log failure
error () {
    echo "`date` ERROR: $@" | tee -a $SENTINEL $HWLOG > /dev/null
    echo "ERROR: $@"
}

#Log failure
warn () {
    echo "`date` WARN: $@" | tee -a $HWLOG > /dev/null
    echo "WARN: $@"
}

#Log Information
info() {
    echo "`date` INFO: $@" | tee -a $HWLOG > /dev/null
    echo "INFO: $@"
}

booterror() {
    error "$1"
    text2screen -c
    text2screen -x 1 -y 1 -s 5 -t "E: $@"
    sleep 300
    reboot
}

printinfo() {
    text2screen -c
    text2screen -x 1 -y 1 -s 1 -t "$@"
}

