#!/bin/bash

set -e
#set -v

LIVE_SNIPPET_DIR=/opt/aus2/incoming/3
BACKUP_DIR=/opt/aus2/snippets/backup

WC=/usr/bin/wc
DATE=/bin/date
TAR=/bin/tar
GREP=/bin/grep
SCP=/usr/bin/scp

currentDate=`$DATE +%Y%m%d`

## We use the shell's expansion capabilites to get a list of other snippet
## directories we may have pushed today... kinda lame, but it works.

pushd $BACKUP_DIR > /dev/null
backupDirCount=`echo $currentDate-nightly-?.* | $GREP -v \? | $WC -w`
popd > /dev/null

## Increment the count by one, for the new snippet backup directory we're
## about to create
let backupDirCount=$backupDirCount+1
backupDirName=$currentDate-nightly-$backupDirCount

# Make the backup. This takes forever, thanks NFS!
# don't forget to update check-sync if you extend the exclude list
pushd $LIVE_SNIPPET_DIR > /dev/null
/usr/bin/time -p -o $BACKUP_DIR/$backupDirName.time $TAR cfj $BACKUP_DIR/$backupDirName.tar.bz2 . \
  --exclude 'Firefox/1.5*' --exclude 'Firefox/2.0*' --exclude 'Firefox/3.0*' \
  --exclude 'Firefox/3.1*' --exclude 'Firefox/3.5*' --exclude 'Thunderbird/1.5*'
popd > /dev/null

# push the file over to Phoenix to aid checking all is in sync there
if [[ 'dm-ausstage01.mozilla.org' == `uname -n` ]]; then
  $SCP -q $BACKUP_DIR/$backupDirName.tar.bz2 dp-ausstage01:$BACKUP_DIR/
fi

exit 0
