#!/bin/bash
#
# This script requires an input of a list of locales. For each locale given it
# will retrieve the current tip-most revision of that locale's repository.
# Locale repositories are assumed to live one level deeper than $L10N_CENTRAL.
# eg. http://hg.mozilla.org/l10n-central/index.cgi/af

L10N_CENTRAL='http://hg.mozilla.org/l10n-central/index.cgi'
DUMP_FILE='l10n-changesets'

if [ -f $DUMP_FILE ]; then
  mv $DUMP_FILE $DUMP_FILE.old
fi

for locale in $@; do
  repo="$L10N_CENTRAL/$locale"
  echo "Running 'hg identify $repo'"
  id=$(hg identify $repo)
  if [ $? -ne 0 ]; then
    echo "  Could not retrieve changeset for '$locale', please fix it manually."
    id="FIXME"
  else
    echo -n "  "
  fi
  echo "$locale $id" | tee -a $DUMP_FILE
done
